// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Rk_OVcvFcnuXhVWL-Qz-eHG-0iWxB3U',
    appId: '1:645857696621:web:aab702d311e51b32a71864',
    messagingSenderId: '645857696621',
    projectId: 'portfolio-32d39',
    authDomain: 'portfolio-32d39.firebaseapp.com',
    storageBucket: 'portfolio-32d39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7s1JfCtfSdBLppboJybn2BlI40OSm-eA',
    appId: '1:645857696621:android:bf74e04341a4fbf3a71864',
    messagingSenderId: '645857696621',
    projectId: 'portfolio-32d39',
    storageBucket: 'portfolio-32d39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCse2PueE5RQ-DuNnVFMWIqGwVj6yKKhVA',
    appId: '1:645857696621:ios:63b732dc68df3daaa71864',
    messagingSenderId: '645857696621',
    projectId: 'portfolio-32d39',
    storageBucket: 'portfolio-32d39.appspot.com',
    iosBundleId: 'com.example.flutterProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCse2PueE5RQ-DuNnVFMWIqGwVj6yKKhVA',
    appId: '1:645857696621:ios:63b732dc68df3daaa71864',
    messagingSenderId: '645857696621',
    projectId: 'portfolio-32d39',
    storageBucket: 'portfolio-32d39.appspot.com',
    iosBundleId: 'com.example.flutterProfile',
  );
}
